name: Publish Workshop Material
on:
  push:
    branches:
      - main
  repository_dispatch:
jobs:
  create-archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build artifact
        run: make material.tar.gz
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          files: material.tar.gz
